### ISSUE TITLE
Boston

### ISSUE THREAD

**Issue by dylanegan** [dylanegan/travel#69]
http://www.belleisleseafood.com, http://www.mrbartley.com, http://www.jplicks.com/default.htm.

**Comment by will** [comment]
@dylanegan I'm here for the week, anything on this list, bar or restaurant, that was memorable in particular?

**Comment by dylanegan** [comment]
@will I didn't get a chance in the end to try out much (as per file). I just remember boozy shakes at Grass Fed with a burger and/or fries. Went to Menton with a few people and that was nice.

@sr might have some tips as he's been to Boston quite a bit.
